AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  AlertSNSTopicArn:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /ffxiv-item-name-database/alert-sns-topic

  BeautifulSoup4LayerArn:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /ffxiv-item-name-database/layer/beautiful-soup-4

Globals:
  Function:
    Runtime: python3.8
    Timeout: 900
    AutoPublishAlias: scrape
    CodeUri: src
    MemorySize: 256
    Environment:
      Variables:
        TMP_DATA_BUCKET_NAME: !Ref TmpDataBucket

Resources:
  CallSFnFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers.call_sfn.handler
      Policies:
        - arn:aws:iam::aws:policy/AWSStepFunctionsFullAccess
      Environment:
        Variables:
          STATE_MACHINE_ARN: !Ref ItemDataScrapeStateMachine

  CallSFnLogStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: log_group.yml
      Parameters:
        FunctionName: !Ref CallSFnFunction
        AlartSnsTopicArn: !Ref AlertSNSTopicArn

  TmpDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays: 90
            Status: Enabled

  ScrapeEorzeaDatabaseFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers.scrape_eorzea_database.handler
      Policies:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
      Layers:
        - !Ref BeautifulSoup4LayerArn

  ScrapeEorzeaDatabaseLogStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: log_group.yml
      Parameters:
        FunctionName: !Ref ScrapeEorzeaDatabaseFunction
        AlartSnsTopicArn: !Ref AlertSNSTopicArn

  ScrapeXivApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers.scrape_xivapi.handler
      Policies:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess

  ScrapeXivApiLogStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: log_group.yml
      Parameters:
        FunctionName: !Ref ScrapeXivApiFunction
        AlartSnsTopicArn: !Ref AlertSNSTopicArn

  MergeEorzeaDatabaseFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers.merge_eorzea_database.handler
      Policies:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
      MemorySize: 3008

  MergeEorzeaDatabaseLogStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: log_group.yml
      Parameters:
        FunctionName: !Ref MergeEorzeaDatabaseFunction
        AlartSnsTopicArn: !Ref AlertSNSTopicArn

  MergeXivApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers.merge_xivapi.handler
      Policies:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
      MemorySize: 3008

  MergeXivApiLogStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: log_group.yml
      Parameters:
        FunctionName: !Ref MergeXivApiFunction
        AlartSnsTopicArn: !Ref AlertSNSTopicArn

  MergeItemDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers.merge_item_data.handler
      Policies:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
      MemorySize: 3008

  MergeItemDataLogStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: log_group.yml
      Parameters:
        FunctionName: !Ref MergeItemDataFunction
        AlartSnsTopicArn: !Ref AlertSNSTopicArn

  ItemDataScrapeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: !Sub states.${AWS::Region}.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaRole

  ItemDataScrapeStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      RoleArn: !GetAtt ItemDataScrapeRole.Arn
      DefinitionString: !Sub |-
        {
          "Comment": "Scrape FF14 Item",
          "StartAt": "ScrapeEorzeaDatabase",
          "States": {
            "ScrapeEorzeaDatabase": {
              "Type": "Task",
              "Resource": "${ScrapeEorzeaDatabaseFunction.Alias}",
              "Next": "CheckScrapeEorzeaDatabase"
            },
            "CheckScrapeEorzeaDatabase": {
              "Type": "Choice",
              "Default": "ScrapeEorzeaDatabase",
              "Choices": [
                {
                  "Variable": "$.database_page",
                  "NumericEquals": 0,
                  "Next": "ScrapeXivApi"
                }
              ]
            },
            "ScrapeXivApi": {
              "Type": "Task",
              "Resource": "${ScrapeXivApiFunction.Alias}",
              "Next": "CheckScrapeXivApi"
            },
            "CheckScrapeXivApi": {
              "Type": "Choice",
              "Default": "ScrapeXivApi",
              "Choices": [
                {
                  "Variable": "$.xivapi_page",
                  "NumericEquals": 0,
                  "Next": "MergeEorzeaDatabase"
                }
              ]
            },
            "MergeEorzeaDatabase": {
              "Type": "Task",
              "Resource": "${MergeEorzeaDatabaseFunction.Alias}",
              "Next": "MergeXivApi"
            },
            "MergeXivApi": {
              "Type": "Task",
              "Resource": "${MergeXivApiFunction.Alias}",
              "Next": "MergeItemData"
            },
            "MergeItemData": {
              "Type": "Task",
              "Resource": "${MergeItemDataFunction.Alias}",
              "End": true
            }
          }
        }